const INCREAMENT = 'INCREAMENT';
const DECREAMENT = 'DECREAMENT';
const RESET = 'RESET';
const INCREAMENT_BY = 'INCREAMENT_BY';
const IS_FETCHING = 'IS_FETCHING';
const FETCH_SUCCESS = 'FETCH_SUCCESS';
const FETCH_FAILED = 'FETCH_FAILED';

export {
	INCREAMENT,
	DECREAMENT,
	RESET,
	INCREAMENT_BY,
	IS_FETCHING,
	FETCH_SUCCESS,
	FETCH_FAILED
};
